<?php

use Illuminate\Database\Seeder;

class UsersTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('users')->delete();
        
        \DB::table('users')->insert(array (
            0 => 
            array (
                'id' => 100,
                'name' => NULL,
                'first_name' => 'Test',
                'last_name' => 'User',
                'middle_name' => 'Project Supervision tool',
                'phone' => NULL,
                'email' => 'testing@project-supervision-tool.com',
                'type' => 'focal_person',
                'location_id' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$10$TMuGZwRiElEtuuHGDzf4sOB6J5gOTPdyQUmeQnh8WJmPNXQRkxSBC',
                'remember_token' => NULL,
                'created_at' => '2021-01-17 06:32:04',
                'updated_at' => '2021-01-17 06:32:04',
                'deleted_at' => NULL,
            ),
            1 => 
            array (
                'id' => 102,
                'name' => NULL,
                'first_name' => 'Beatrice',
                'last_name' => 'Mkumbo',
                'middle_name' => 'Charles',
                'phone' => '248-402-0400 x528',
                'email' => 'charsbeaty@gmail.com',
                'type' => 'focal_person',
                'location_id' => NULL,
                'email_verified_at' => '2020-11-16 08:14:25',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            2 => 
            array (
                'id' => 103,
                'name' => NULL,
                'first_name' => 'Edgar',
                'last_name' => 'Mlowe',
                'middle_name' => 'Vitus',
                'phone' => '689-885-3690',
                'email' => 'mloweedgarvitus@gmail.com',
                'type' => 'focal_person',
                'location_id' => NULL,
                'email_verified_at' => '2020-11-16 08:14:25',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            3 => 
            array (
                'id' => 1,
                'name' => 'Elmira Wunsch',
                'first_name' => 'Lenny',
                'last_name' => 'Zboncak',
                'middle_name' => 'Brennan',
                'phone' => '604.597.1772 x87636',
                'email' => 'devon.ohara@example.net',
                'type' => 'focal_person',
                'location_id' => NULL,
                'email_verified_at' => '2021-01-17 10:23:34',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'remember_token' => 'crH0VUBAcP',
                'created_at' => '2021-01-17 10:23:34',
                'updated_at' => '2021-01-17 10:23:34',
                'deleted_at' => NULL,
            ),
            4 => 
            array (
                'id' => 2,
                'name' => 'Stephany Grant DDS',
                'first_name' => 'Xzavier',
                'last_name' => 'Kuhn',
                'middle_name' => 'Daphney',
            'phone' => '(717) 330-9638',
                'email' => 'parisian.elvie@example.org',
                'type' => 'focal_person',
                'location_id' => NULL,
                'email_verified_at' => '2021-01-17 10:23:34',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'remember_token' => 'egR8UPtind',
                'created_at' => '2021-01-17 10:23:34',
                'updated_at' => '2021-01-17 10:23:34',
                'deleted_at' => NULL,
            ),
            5 => 
            array (
                'id' => 3,
                'name' => 'Alphonso Jacobson',
                'first_name' => 'Remington',
                'last_name' => 'Sauer',
                'middle_name' => 'Lesly',
                'phone' => '643-550-5734 x864',
                'email' => 'mallie14@example.com',
                'type' => 'focal_person',
                'location_id' => NULL,
                'email_verified_at' => '2021-01-17 10:23:34',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'remember_token' => 'tjn2jdWU64',
                'created_at' => '2021-01-17 10:23:34',
                'updated_at' => '2021-01-17 10:23:34',
                'deleted_at' => NULL,
            ),
            6 => 
            array (
                'id' => 4,
                'name' => 'Elsa Adams',
                'first_name' => 'Nico',
                'last_name' => 'Fahey',
                'middle_name' => 'Michaela',
                'phone' => '526-993-1325',
                'email' => 'moses99@example.net',
                'type' => 'focal_person',
                'location_id' => NULL,
                'email_verified_at' => '2021-01-17 10:23:34',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'remember_token' => 'L5zsRFwGX8',
                'created_at' => '2021-01-17 10:23:34',
                'updated_at' => '2021-01-17 10:23:34',
                'deleted_at' => NULL,
            ),
            7 => 
            array (
                'id' => 5,
                'name' => 'Dr. Virgil Waelchi DVM',
                'first_name' => 'Adella',
                'last_name' => 'Connelly',
                'middle_name' => 'Leanna',
                'phone' => '421-325-0128',
                'email' => 'breitenberg.emiliano@example.org',
                'type' => 'focal_person',
                'location_id' => NULL,
                'email_verified_at' => '2021-01-17 10:23:34',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'remember_token' => 'joBeF287xM',
                'created_at' => '2021-01-17 10:23:34',
                'updated_at' => '2021-01-17 10:23:34',
                'deleted_at' => NULL,
            ),
            8 => 
            array (
                'id' => 6,
                'name' => 'Freda Crona',
                'first_name' => 'Dandre',
                'last_name' => 'Collins',
                'middle_name' => 'Jordane',
                'phone' => '1-834-644-5734 x841',
                'email' => 'krystina59@example.org',
                'type' => 'focal_person',
                'location_id' => NULL,
                'email_verified_at' => '2021-01-17 10:23:34',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'remember_token' => 'Iac2MDR0M8',
                'created_at' => '2021-01-17 10:23:34',
                'updated_at' => '2021-01-17 10:23:34',
                'deleted_at' => NULL,
            ),
            9 => 
            array (
                'id' => 7,
                'name' => 'Clotilde Haag',
                'first_name' => 'Waylon',
                'last_name' => 'Beatty',
                'middle_name' => 'Orval',
                'phone' => '265-892-5278 x02924',
                'email' => 'jrath@example.com',
                'type' => 'focal_person',
                'location_id' => NULL,
                'email_verified_at' => '2021-01-17 10:23:34',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'remember_token' => 'm7XFK17HcA',
                'created_at' => '2021-01-17 10:23:34',
                'updated_at' => '2021-01-17 10:23:34',
                'deleted_at' => NULL,
            ),
            10 => 
            array (
                'id' => 8,
                'name' => 'Daisy Flatley',
                'first_name' => 'Cathy',
                'last_name' => 'Dickinson',
                'middle_name' => 'Salma',
            'phone' => '+1 (604) 374-7275',
                'email' => 'johnson.hilda@example.com',
                'type' => 'focal_person',
                'location_id' => NULL,
                'email_verified_at' => '2021-01-17 10:23:34',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'remember_token' => 'V7mvobe8Lh',
                'created_at' => '2021-01-17 10:23:34',
                'updated_at' => '2021-01-17 10:23:34',
                'deleted_at' => NULL,
            ),
            11 => 
            array (
                'id' => 9,
                'name' => 'Mrs. Idell Schmidt Jr.',
                'first_name' => 'Justyn',
                'last_name' => 'Yost',
                'middle_name' => 'Lily',
                'phone' => '1-442-692-3915',
                'email' => 'mauricio.prohaska@example.org',
                'type' => 'focal_person',
                'location_id' => NULL,
                'email_verified_at' => '2021-01-17 10:23:34',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'remember_token' => 't0wABoL56U',
                'created_at' => '2021-01-17 10:23:34',
                'updated_at' => '2021-01-17 10:23:34',
                'deleted_at' => NULL,
            ),
            12 => 
            array (
                'id' => 10,
                'name' => 'Bernadine Miller',
                'first_name' => 'Adela',
                'last_name' => 'Abernathy',
                'middle_name' => 'Bennett',
                'phone' => '318.618.0536',
                'email' => 'casper.trey@example.net',
                'type' => 'focal_person',
                'location_id' => NULL,
                'email_verified_at' => '2021-01-17 10:23:34',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'remember_token' => 'd5dwD4A1hq',
                'created_at' => '2021-01-17 10:23:34',
                'updated_at' => '2021-01-17 10:23:34',
                'deleted_at' => NULL,
            ),
            13 => 
            array (
                'id' => 11,
                'name' => 'Ms. Marie Johnson I',
                'first_name' => 'Al',
                'last_name' => 'Turner',
                'middle_name' => 'Lavern',
                'phone' => '+18323707399',
                'email' => 'schinner.jeramy@example.net',
                'type' => 'focal_person',
                'location_id' => NULL,
                'email_verified_at' => '2021-01-17 10:23:34',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'remember_token' => 'Cxurc6BO79',
                'created_at' => '2021-01-17 10:23:34',
                'updated_at' => '2021-01-17 10:23:34',
                'deleted_at' => NULL,
            ),
            14 => 
            array (
                'id' => 12,
                'name' => 'Luigi Bergnaum',
                'first_name' => 'Felicia',
                'last_name' => 'Hyatt',
                'middle_name' => 'Dustin',
                'phone' => '1-447-702-2142',
                'email' => 'trantow.keira@example.com',
                'type' => 'focal_person',
                'location_id' => NULL,
                'email_verified_at' => '2021-01-17 10:23:34',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'remember_token' => 'K4sUGmlyUD',
                'created_at' => '2021-01-17 10:23:34',
                'updated_at' => '2021-01-17 10:23:34',
                'deleted_at' => NULL,
            ),
            15 => 
            array (
                'id' => 13,
                'name' => 'Tristian Cormier',
                'first_name' => 'Alize',
                'last_name' => 'Bahringer',
                'middle_name' => 'Amari',
            'phone' => '(856) 990-4827',
                'email' => 'joana41@example.net',
                'type' => 'focal_person',
                'location_id' => NULL,
                'email_verified_at' => '2021-01-17 10:23:34',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'remember_token' => 'z7tWYSLVZ6',
                'created_at' => '2021-01-17 10:23:34',
                'updated_at' => '2021-01-17 10:23:34',
                'deleted_at' => NULL,
            ),
            16 => 
            array (
                'id' => 14,
                'name' => 'Nayeli Walker DVM',
                'first_name' => 'Ansel',
                'last_name' => 'Lowe',
                'middle_name' => 'Bruce',
                'phone' => '358.250.7829 x765',
                'email' => 'xstanton@example.org',
                'type' => 'focal_person',
                'location_id' => NULL,
                'email_verified_at' => '2021-01-17 10:23:34',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'remember_token' => 'FFji1jnkm0',
                'created_at' => '2021-01-17 10:23:34',
                'updated_at' => '2021-01-17 10:23:34',
                'deleted_at' => NULL,
            ),
            17 => 
            array (
                'id' => 15,
                'name' => 'Casandra Baumbach',
                'first_name' => 'Dortha',
                'last_name' => 'Ryan',
                'middle_name' => 'Gavin',
                'phone' => '1-985-299-6096 x9187',
                'email' => 'dsatterfield@example.net',
                'type' => 'focal_person',
                'location_id' => NULL,
                'email_verified_at' => '2021-01-17 10:23:34',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'remember_token' => 'fAYjrkMtE4',
                'created_at' => '2021-01-17 10:23:34',
                'updated_at' => '2021-01-17 10:23:34',
                'deleted_at' => NULL,
            ),
            18 => 
            array (
                'id' => 16,
                'name' => 'Mabelle Cronin',
                'first_name' => 'Charlie',
                'last_name' => 'Rodriguez',
                'middle_name' => 'Annabelle',
                'phone' => '+1-912-416-1026',
                'email' => 'rudy.paucek@example.net',
                'type' => 'focal_person',
                'location_id' => NULL,
                'email_verified_at' => '2021-01-17 10:23:34',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'remember_token' => 'EBjbbZpcNz',
                'created_at' => '2021-01-17 10:23:34',
                'updated_at' => '2021-01-17 10:23:34',
                'deleted_at' => NULL,
            ),
            19 => 
            array (
                'id' => 17,
                'name' => 'Dr. Elva Schowalter',
                'first_name' => 'Clementine',
                'last_name' => 'Ernser',
                'middle_name' => 'Wava',
                'phone' => '664-362-0156 x669',
                'email' => 'angel97@example.com',
                'type' => 'focal_person',
                'location_id' => NULL,
                'email_verified_at' => '2021-01-17 10:23:34',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'remember_token' => '008E1LILyq',
                'created_at' => '2021-01-17 10:23:34',
                'updated_at' => '2021-01-17 10:23:34',
                'deleted_at' => NULL,
            ),
            20 => 
            array (
                'id' => 18,
                'name' => 'Jaquan Reichel',
                'first_name' => 'Everett',
                'last_name' => 'Nolan',
                'middle_name' => 'Ephraim',
                'phone' => '1-978-617-4679 x28569',
                'email' => 'bprice@example.net',
                'type' => 'focal_person',
                'location_id' => NULL,
                'email_verified_at' => '2021-01-17 10:23:34',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'remember_token' => 'YAjCfjSJYv',
                'created_at' => '2021-01-17 10:23:34',
                'updated_at' => '2021-01-17 10:23:34',
                'deleted_at' => NULL,
            ),
        ));
        
        
    }
}