version: '3'

services:
  db:
    image: postgis/postgis
    container_name: project-supervision-tool_db
    restart: unless-stopped
    volumes:
      - "project_supervision_tool_db_data:/var/lib/postgresql/data"
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    ports:
      - "5432:5432"


  php:
    build: .
    image: project-supervision-tool
    container_name: project-superviosion-tool
    restart: unless-stopped
    depends_on:
      - db
    volumes:
      - ./:/var/www

  web:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d
      - letsencrypt/:/letsencrypt
      - certs:/etc/nginx/ssl/:ro

  certbot:
    image: certbot/certbot:latest
    volumes:
      - letsencrypt/:/var/www/certbot/:rw
      - certs:/etc/letsencrypt/:rw

volumes:
  project_supervision_tool_db_data:
  letsencrypt:
  certs:


