version: '3'

services:
  db:
    image: postgis/postgis
    container_name: postgres-tukutane
    restart: unless-stopped
    volumes:
      - "tukutane-dbdata:/var/lib/postgresql/data"
    environment:
      - POSTGRES_USER=postgres-tukutane
      - POSTGRES_PASSWORD=StrongPass@tukutane
      - POSTGRES_DB=tukutane
    ports:
      - "5432:5432"

  php:
    build: .
    image: project-supervision-tool
    container_name: project-superviosion-tool
    restart: unless-stopped
    depends_on:
      - db
    volumes:
      - ./:/var/www

  web:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    volumes:
      - ./:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/

volumes:
  tukutane-dbdata:
